### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by manmartgarc** [vhewes/pynuml#26]
Not sure if this is an issue with this but when I tried running `pip install pynuml` I got to the end of the installation step and there was an issue installing `mpi4py` since it expects some MPI files to be present in the machine

**Comment by vhewes** [comment]
Hi Manuel! Yes, you'll need an MPI installation in order to install `mpi4py` via pip. If you don't have one, I'd recommend using Anaconda to install `mpi4py`, since conda is able to install the underlying HDF5 dependencies as well.

If it helps, I maintain a docker image at `vhewes/numl` [here](https://hub.docker.com/r/vhewes/numl/tags) with the necessary environment, and I'd recommend the `torch2.0-cu11.7` tag. You can also see the Dockerfile used to build this image [here](https://github.com/vhewes/numl-docker/blob/main/Dockerfile), if you want to see some useful code snippets for how the dependencies are installed.

Let me know if this helps you to get up and running!

**Comment by manmartgarc** [comment]
> Hi Manuel! Yes, you'll need an MPI installation in order to install `mpi4py` via pip. If you don't have one, I'd recommend using Anaconda to install `mpi4py`, since conda is able to install the underlying HDF5 dependencies as well.
> 
> If it helps, I maintain a docker image at `vhewes/numl` [here](https://hub.docker.com/r/vhewes/numl/tags) with the necessary environment, and I'd recommend the `torch2.0-cu11.7` tag. You can also see the Dockerfile used to build this image [here](https://github.com/vhewes/numl-docker/blob/main/Dockerfile), if you want to see some useful code snippets for how the dependencies are installed.
> 
> Let me know if this helps you to get up and running!

Awesome thanks! I managed to get it working using `conda` to install the MPI libraries.
